//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mes.Model.StoredProcedure
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MesProc : DbContext
    {
        public MesProc()
            : base("name=MesProc")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Backup_CCMMES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Backup_CCMMES");
        }
    
        public virtual ObjectResult<BatchUseMatD_Result> BatchUseMatD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BatchUseMatD_Result>("BatchUseMatD");
        }
    
        public virtual ObjectResult<BatchUseMatDs_Result> BatchUseMatDs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BatchUseMatDs_Result>("BatchUseMatDs");
        }
    
        public virtual ObjectResult<BatchUseMatDss_Result> BatchUseMatDss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BatchUseMatDss_Result>("BatchUseMatDss");
        }
    
        public virtual int Find_Lock()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Find_Lock");
        }
    
        public virtual int GetSerialNumberBySNID(string fC_SNID, string fC_Date, Nullable<int> fC_CureentMAXNo, ObjectParameter mAXRECORD)
        {
            var fC_SNIDParameter = fC_SNID != null ?
                new ObjectParameter("FC_SNID", fC_SNID) :
                new ObjectParameter("FC_SNID", typeof(string));
    
            var fC_DateParameter = fC_Date != null ?
                new ObjectParameter("FC_Date", fC_Date) :
                new ObjectParameter("FC_Date", typeof(string));
    
            var fC_CureentMAXNoParameter = fC_CureentMAXNo.HasValue ?
                new ObjectParameter("FC_CureentMAXNo", fC_CureentMAXNo) :
                new ObjectParameter("FC_CureentMAXNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSerialNumberBySNID", fC_SNIDParameter, fC_DateParameter, fC_CureentMAXNoParameter, mAXRECORD);
        }
    
        public virtual int GetSnPlog(string poNo, string batchNo, string pSCode, string barCode, string chkMac, Nullable<System.DateTime> fromTime, Nullable<System.DateTime> toTime)
        {
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var batchNoParameter = batchNo != null ?
                new ObjectParameter("batchNo", batchNo) :
                new ObjectParameter("batchNo", typeof(string));
    
            var pSCodeParameter = pSCode != null ?
                new ObjectParameter("PSCode", pSCode) :
                new ObjectParameter("PSCode", typeof(string));
    
            var barCodeParameter = barCode != null ?
                new ObjectParameter("barCode", barCode) :
                new ObjectParameter("barCode", typeof(string));
    
            var chkMacParameter = chkMac != null ?
                new ObjectParameter("chkMac", chkMac) :
                new ObjectParameter("chkMac", typeof(string));
    
            var fromTimeParameter = fromTime.HasValue ?
                new ObjectParameter("FromTime", fromTime) :
                new ObjectParameter("FromTime", typeof(System.DateTime));
    
            var toTimeParameter = toTime.HasValue ?
                new ObjectParameter("ToTime", toTime) :
                new ObjectParameter("ToTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSnPlog", poNoParameter, batchNoParameter, pSCodeParameter, barCodeParameter, chkMacParameter, fromTimeParameter, toTimeParameter);
        }
    
        public virtual int p_lockinfo(Nullable<bool> kill_lock_spid, Nullable<bool> show_spid_if_nolock)
        {
            var kill_lock_spidParameter = kill_lock_spid.HasValue ?
                new ObjectParameter("kill_lock_spid", kill_lock_spid) :
                new ObjectParameter("kill_lock_spid", typeof(bool));
    
            var show_spid_if_nolockParameter = show_spid_if_nolock.HasValue ?
                new ObjectParameter("show_spid_if_nolock", show_spid_if_nolock) :
                new ObjectParameter("show_spid_if_nolock", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_lockinfo", kill_lock_spidParameter, show_spid_if_nolockParameter);
        }
    
        public virtual int PR_AutoTran()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_AutoTran");
        }
    
        public virtual int PR_ClearData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ClearData");
        }
    
        public virtual int PR_ClearFPoData(string factory)
        {
            var factoryParameter = factory != null ?
                new ObjectParameter("Factory", factory) :
                new ObjectParameter("Factory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ClearFPoData", factoryParameter);
        }
    
        public virtual int PR_ClearYWData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_ClearYWData");
        }
    
        public virtual int PR_CreateTestData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_CreateTestData");
        }
    
        public virtual int PR_HR_GetSPCDept(string deptID, string lvl, string deptType)
        {
            var deptIDParameter = deptID != null ?
                new ObjectParameter("DeptID", deptID) :
                new ObjectParameter("DeptID", typeof(string));
    
            var lvlParameter = lvl != null ?
                new ObjectParameter("Lvl", lvl) :
                new ObjectParameter("Lvl", typeof(string));
    
            var deptTypeParameter = deptType != null ?
                new ObjectParameter("DeptType", deptType) :
                new ObjectParameter("DeptType", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_HR_GetSPCDept", deptIDParameter, lvlParameter, deptTypeParameter);
        }
    
        public virtual int PR_PRD_BATCHMOVE(string moveNo, string oprNo, ObjectParameter oprResult, ObjectParameter err)
        {
            var moveNoParameter = moveNo != null ?
                new ObjectParameter("MoveNo", moveNo) :
                new ObjectParameter("MoveNo", typeof(string));
    
            var oprNoParameter = oprNo != null ?
                new ObjectParameter("OprNo", oprNo) :
                new ObjectParameter("OprNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_BATCHMOVE", moveNoParameter, oprNoParameter, oprResult, err);
        }
    
        public virtual int PR_PRD_LCDRateData(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_PRD_LCDRateData_1(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData_1", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_PRD_LCDRateData_2(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData_2", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_PRD_LCDRateData_3(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData_3", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_PRD_LCDRateData_3备份20170802(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData_3备份20170802", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_PRD_LCDRateData_3备份20180118(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end, string workNo, string poType, string eRPPo, string poNo, string soNo, string pNo, string shape, string ngGroup)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var workNoParameter = workNo != null ?
                new ObjectParameter("WorkNo", workNo) :
                new ObjectParameter("WorkNo", typeof(string));
    
            var poTypeParameter = poType != null ?
                new ObjectParameter("poType", poType) :
                new ObjectParameter("poType", typeof(string));
    
            var eRPPoParameter = eRPPo != null ?
                new ObjectParameter("ERPPo", eRPPo) :
                new ObjectParameter("ERPPo", typeof(string));
    
            var poNoParameter = poNo != null ?
                new ObjectParameter("PoNo", poNo) :
                new ObjectParameter("PoNo", typeof(string));
    
            var soNoParameter = soNo != null ?
                new ObjectParameter("SoNo", soNo) :
                new ObjectParameter("SoNo", typeof(string));
    
            var pNoParameter = pNo != null ?
                new ObjectParameter("PNo", pNo) :
                new ObjectParameter("PNo", typeof(string));
    
            var shapeParameter = shape != null ?
                new ObjectParameter("Shape", shape) :
                new ObjectParameter("Shape", typeof(string));
    
            var ngGroupParameter = ngGroup != null ?
                new ObjectParameter("NgGroup", ngGroup) :
                new ObjectParameter("NgGroup", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_LCDRateData_3备份20180118", facParameter, codeNoParameter, startParameter, endParameter, workNoParameter, poTypeParameter, eRPPoParameter, poNoParameter, soNoParameter, pNoParameter, shapeParameter, ngGroupParameter);
        }
    
        public virtual int PR_Prd_UpdDayPlan(string planNo, ObjectParameter oprResult, ObjectParameter err)
        {
            var planNoParameter = planNo != null ?
                new ObjectParameter("planNo", planNo) :
                new ObjectParameter("planNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Prd_UpdDayPlan", planNoParameter, oprResult, err);
        }
    
        public virtual int PR_PRD_WorkcenterOutData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_PRD_WorkcenterOutData");
        }
    
        public virtual int PR_RPT_BatchRate(string fC_ERPPO, string fC_PONo, string fC_SONo, string fC_PNo, string fC_Shape, string fC_POType, Nullable<System.DateTime> sFD_FDate, Nullable<System.DateTime> eFD_FDate, string fC_Factory, Nullable<bool> noFGBatch, string fC_NGGroup, Nullable<bool> useExt, string setExtsFC_Value)
        {
            var fC_ERPPOParameter = fC_ERPPO != null ?
                new ObjectParameter("FC_ERPPO", fC_ERPPO) :
                new ObjectParameter("FC_ERPPO", typeof(string));
    
            var fC_PONoParameter = fC_PONo != null ?
                new ObjectParameter("FC_PONo", fC_PONo) :
                new ObjectParameter("FC_PONo", typeof(string));
    
            var fC_SONoParameter = fC_SONo != null ?
                new ObjectParameter("FC_SONo", fC_SONo) :
                new ObjectParameter("FC_SONo", typeof(string));
    
            var fC_PNoParameter = fC_PNo != null ?
                new ObjectParameter("FC_PNo", fC_PNo) :
                new ObjectParameter("FC_PNo", typeof(string));
    
            var fC_ShapeParameter = fC_Shape != null ?
                new ObjectParameter("FC_Shape", fC_Shape) :
                new ObjectParameter("FC_Shape", typeof(string));
    
            var fC_POTypeParameter = fC_POType != null ?
                new ObjectParameter("FC_POType", fC_POType) :
                new ObjectParameter("FC_POType", typeof(string));
    
            var sFD_FDateParameter = sFD_FDate.HasValue ?
                new ObjectParameter("SFD_FDate", sFD_FDate) :
                new ObjectParameter("SFD_FDate", typeof(System.DateTime));
    
            var eFD_FDateParameter = eFD_FDate.HasValue ?
                new ObjectParameter("EFD_FDate", eFD_FDate) :
                new ObjectParameter("EFD_FDate", typeof(System.DateTime));
    
            var fC_FactoryParameter = fC_Factory != null ?
                new ObjectParameter("FC_Factory", fC_Factory) :
                new ObjectParameter("FC_Factory", typeof(string));
    
            var noFGBatchParameter = noFGBatch.HasValue ?
                new ObjectParameter("NoFGBatch", noFGBatch) :
                new ObjectParameter("NoFGBatch", typeof(bool));
    
            var fC_NGGroupParameter = fC_NGGroup != null ?
                new ObjectParameter("FC_NGGroup", fC_NGGroup) :
                new ObjectParameter("FC_NGGroup", typeof(string));
    
            var useExtParameter = useExt.HasValue ?
                new ObjectParameter("useExt", useExt) :
                new ObjectParameter("useExt", typeof(bool));
    
            var setExtsFC_ValueParameter = setExtsFC_Value != null ?
                new ObjectParameter("setExtsFC_Value", setExtsFC_Value) :
                new ObjectParameter("setExtsFC_Value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_RPT_BatchRate", fC_ERPPOParameter, fC_PONoParameter, fC_SONoParameter, fC_PNoParameter, fC_ShapeParameter, fC_POTypeParameter, sFD_FDateParameter, eFD_FDateParameter, fC_FactoryParameter, noFGBatchParameter, fC_NGGroupParameter, useExtParameter, setExtsFC_ValueParameter);
        }
    
        public virtual int Pr_Sys_AllowData(string userID, ObjectParameter currFac)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Sys_AllowData", userIDParameter, currFac);
        }
    
        public virtual int PR_SYS_AUTONO(string tableName, string columnName, Nullable<int> autoNum, string extParams, ObjectParameter autoNo, ObjectParameter errorInfo)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            var columnNameParameter = columnName != null ?
                new ObjectParameter("ColumnName", columnName) :
                new ObjectParameter("ColumnName", typeof(string));
    
            var autoNumParameter = autoNum.HasValue ?
                new ObjectParameter("AutoNum", autoNum) :
                new ObjectParameter("AutoNum", typeof(int));
    
            var extParamsParameter = extParams != null ?
                new ObjectParameter("ExtParams", extParams) :
                new ObjectParameter("ExtParams", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_SYS_AUTONO", tableNameParameter, columnNameParameter, autoNumParameter, extParamsParameter, autoNo, errorInfo);
        }
    
        public virtual int Pr_Sys_GetCBusDept(string userID, ObjectParameter currFac)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pr_Sys_GetCBusDept", userIDParameter, currFac);
        }
    
        public virtual ObjectResult<PR_Sys_RoleModule_Result> PR_Sys_RoleModule(string roleID)
        {
            var roleIDParameter = roleID != null ?
                new ObjectParameter("roleID", roleID) :
                new ObjectParameter("roleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Sys_RoleModule_Result>("PR_Sys_RoleModule", roleIDParameter);
        }
    
        public virtual ObjectResult<PR_Sys_RoleModuleDetail_Result> PR_Sys_RoleModuleDetail(string roleID)
        {
            var roleIDParameter = roleID != null ?
                new ObjectParameter("roleID", roleID) :
                new ObjectParameter("roleID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Sys_RoleModuleDetail_Result>("PR_Sys_RoleModuleDetail", roleIDParameter);
        }
    
        public virtual int PR_SYS_TableSize()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_SYS_TableSize");
        }
    
        public virtual ObjectResult<PR_Sys_UserModule_Result> PR_Sys_UserModule(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PR_Sys_UserModule_Result>("PR_Sys_UserModule", userIDParameter);
        }
    
        public virtual int PR_Upd_GYERPTOMES(string pONo, ObjectParameter result, ObjectParameter errorInfo)
        {
            var pONoParameter = pONo != null ?
                new ObjectParameter("PONo", pONo) :
                new ObjectParameter("PONo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PR_Upd_GYERPTOMES", pONoParameter, result, errorInfo);
        }
    
        public virtual int ProFirstPrdRate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProFirstPrdRate");
        }
    
        public virtual int Rpt_MachineReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rpt_MachineReport");
        }
    
        public virtual int Rpt_MachineReportBackup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rpt_MachineReportBackup");
        }
    
        public virtual ObjectResult<Rpt_SetUpRateNewIsLink_Result> Rpt_SetUpRateNewIsLink(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_SetUpRateNewIsLink_Result>("Rpt_SetUpRateNewIsLink", facParameter, codeNoParameter, startParameter, endParameter);
        }
    
        public virtual ObjectResult<Rpt_SetUpRateNewNoLink_Result> Rpt_SetUpRateNewNoLink(string fac, string codeNo, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var facParameter = fac != null ?
                new ObjectParameter("Fac", fac) :
                new ObjectParameter("Fac", typeof(string));
    
            var codeNoParameter = codeNo != null ?
                new ObjectParameter("CodeNo", codeNo) :
                new ObjectParameter("CodeNo", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rpt_SetUpRateNewNoLink_Result>("Rpt_SetUpRateNewNoLink", facParameter, codeNoParameter, startParameter, endParameter);
        }
    
        public virtual int Rpt_UserUPHReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Rpt_UserUPHReport");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_TongBuCcmPO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TongBuCcmPO");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int sp_zyhistoty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_zyhistoty");
        }
    
        public virtual int sp_zyhistoty2020Q1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_zyhistoty2020Q1");
        }
    
        public virtual int sp_zyhistoty2020Q2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_zyhistoty2020Q2");
        }
    
        public virtual int sp_zyhistoty2020Y()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_zyhistoty2020Y");
        }
    }
}
